language: ruby
rvm:
  - 2.1

before_install:
  - gem update --system
  - gem --version

script: ./toolbelt/travisBuild.sh

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
